const ExcelJS = require('exceljs');
const PDFDocument = require('pdfkit');
const { Parser } = require('json2csv');
const Transaction = require('../models/Transaction');

// Export to CSV
const exportToCSV = async (userId, filters = {}) => {
  const query = { user: userId, isDeleted: false, ...filters };
  const transactions = await Transaction.find(query).sort({ date: -1 });
  
  const fields = [
    'date', 'description', 'amount', 'type', 'category', 
    'subcategory', 'paymentMethod', 'notes', 'tags', 'createdAt'
  ];
  
  const opts = { fields };
  const parser = new Parser(opts);
  return parser.parse(transactions);
};

// Export to Excel
const exportToExcel = async (userId, filters = {}) => {
  const query = { user: userId, isDeleted: false, ...filters };
  const transactions = await Transaction.find(query).sort({ date: -1 });
  
  const workbook = new ExcelJS.Workbook();
  const worksheet = workbook.addWorksheet('Transactions');
  
  // Define columns
  worksheet.columns = [
    { header: 'Date', key: 'date', width: 15 },
    { header: 'Description', key: 'description', width: 30 },
    { header: 'Amount', key: 'amount', width: 15 },
    { header: 'Type', key: 'type', width: 10 },
    { header: 'Category', key: 'category', width: 20 },
    { header: 'Subcategory', key: 'subcategory', width: 20 },
    { header: 'Payment Method', key: 'paymentMethod', width: 15 },
    { header: 'Notes', key: 'notes', width: 30 },
    { header: 'Tags', key: 'tags', width: 20 },
    { header: 'Created', key: 'createdAt', width: 20 }
  ];
  
  // Add rows
  transactions.forEach(transaction => {
    worksheet.addRow({
      date: transaction.date.toLocaleDateString(),
      description: transaction.description,
      amount: transaction.amount,
      type: transaction.type,
      category: transaction.category,
      subcategory: transaction.subcategory || '',
      paymentMethod: transaction.paymentMethod,
      notes: transaction.notes || '',
      tags: transaction.tags?.join(', ') || '',
      createdAt: transaction.createdAt.toLocaleDateString()
    });
  });
  
  // Style header row
  worksheet.getRow(1).font = { bold: true };
  worksheet.getRow(1).fill = {
    type: 'pattern',
    pattern: 'solid',
    fgColor: { argb: 'FF4F46E5' }
  };
  
  return workbook;
};

// Export to PDF
const exportToPDF = async (userId, filters = {}) => {
  const query = { user: userId, isDeleted: false, ...filters };
  const transactions = await Transaction.find(query).sort({ date: -1 });
  
  // Get summary
  const totalIncome = transactions
    .filter(t => t.type === 'income')
    .reduce((sum, t) => sum + t.amount, 0);
    
  const totalExpense = transactions
    .filter(t => t.type === 'expense')
    .reduce((sum, t) => sum + t.amount, 0);
  
  // Create PDF
  const doc = new PDFDocument({ margin: 50 });
  
  // Header
  doc.fontSize(20).text('TrackIt - Transaction Report', { align: 'center' });
  doc.moveDown();
  doc.fontSize(12).text(`Generated: ${new Date().toLocaleString()}`, { align: 'center' });
  doc.moveDown();
  
  // Summary
  doc.fontSize(14).text('Summary', { underline: true });
  doc.fontSize(12);
  doc.text(`Total Income: $${totalIncome.toFixed(2)}`);
  doc.text(`Total Expense: $${totalExpense.toFixed(2)}`);
  doc.text(`Net Balance: $${(totalIncome - totalExpense).toFixed(2)}`);
  doc.moveDown();
  
  // Transactions table
  doc.fontSize(14).text('Transactions', { underline: true });
  doc.fontSize(10);
  
  let y = doc.y;
  const startX = 50;
  
  // Headers
  doc.font('Helvetica-Bold');
  doc.text('Date', startX, y);
  doc.text('Description', startX + 80, y);
  doc.text('Amount', startX + 250, y);
  doc.text('Category', startX + 330, y);
  doc.font('Helvetica');
  
  y += 20;
  
  // Rows
  transactions.slice(0, 50).forEach(transaction => {
    if (y > 700) {
      doc.addPage();
      y = 50;
    }
    
    doc.text(transaction.date.toLocaleDateString(), startX, y);
    doc.text(transaction.description.substring(0, 30), startX + 80, y);
    doc.text(`$${transaction.amount.toFixed(2)}`, startX + 250, y);
    doc.text(transaction.category, startX + 330, y);
    y += 20;
  });
  
  // Footer
  doc.fontSize(8).text(
    `Report generated by TrackIt - ${transactions.length} transactions shown`,
    50,
    doc.page.height - 50,
    { align: 'center' }
  );
  
  return doc;
};

module.exports = { exportToCSV, exportToExcel, exportToPDF };